default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sinatra_development

test:
  <<: *default
  database: sinatra_test

production:
  <<: *default
  database: sinatra_production

profiler:
  <<: *default
  database: sinatra_development
